# Generated by Django 5.0.6 on 2024-06-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
